name: draft release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-draft:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "./go.mod"
          cache: true
          cache-dependency-path: "./go.sum"

      - name: Install GOX
        run: go install github.com/mitchellh/gox@latest

      - name: Multi-target Build
        run: VERSION_TAG=${GITHUB_REF#refs/tags/} make release

      - name: List Files
        run: ls ${{ github.workspace }}/dist

      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload --clobber ${GITHUB_REF#refs/tags/} ./dist/*
